"""Create hisotory message table

Revision ID: a2062cdfea23
Revises: 
Create Date: 2023-11-02 01:50:25.905496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2062cdfea23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=5000), nullable=False),
    sa.Column('message_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_history_id'), 'message_history', ['id'], unique=False)
    op.create_index(op.f('ix_message_history_user_email'), 'message_history', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_history_user_email'), table_name='message_history')
    op.drop_index(op.f('ix_message_history_id'), table_name='message_history')
    op.drop_table('message_history')
    # ### end Alembic commands ###
